project:
  type: website
  output-dir: docs

website:
  title: "Kelcie Ralph, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Teaching
      - href: blogposts.qmd
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full
